def reverse_string(input_str):
    '''
    Reverses the input string
    Parameters:
        input_str(str): the input string to be reversed
    Returns:
        str: reversed string
    '''
    reversed_str= input_str[::-1]
    reversed_str = f"The reversed string is {reversed_str}.\n This Result was generated by the tool \"reverse_string\" "
    return reversed_str